manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: rschenk
      url-base: https://github.com/rschenk
    - name: carrefinho
      url-base: https://github.com/carrefinho
#    - name: amrithvenkat
#      url-base: https://github.com/amrithvenkat

  projects:
    - name: zmk
      remote: zmkfirmware
#      revision: v0.3
      revision: main # 4.x
      import: app/west.yml

    # Raytac MDBT50Q
    - name: zmk-component-raytac-dongle
      remote: rschenk
#      revision: v0.3
      revision: v0.4 # 4.x

    # GC9A01A
#    - name: gc9a01a_zephyr_driver
#      remote: amrithvenkat
#      revision: main

  self:
    path: config
